"""add document retry_count

Revision ID: b950156e2817
Revises: f4f0424632f6
Create Date: 2026-08-25 17:53:03.054768

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b950156e2817'
down_revision: str | Sequence[str] | None = 'f4f0424632f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated): existing rows
    # need a value for this new NOT NULL column too, not just new ones.
    op.add_column(
        'documents', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'retry_count')
    # ### end Alembic commands ###
